### ISSUE TITLE
Actual operator character

### ISSUE THREAD

**Issue by michaelfig** [tc39/proposal-wavy-dot#4]
If `!` has an undesired conflict with TypeScript, we may want to use something like `~` as a replacement.  Nobody seems to use that as an infix operator yet.

Should we document this in Caveats?

**Comment by michaelfig** [comment]
@erights, @FUDCo, any thoughts?

**Comment by michaelfig** [comment]
`~` is more wavy, too.

**Comment by FUDCo** [comment]
This may be worth keeping in mind as a fallback, if `!` won't fly.  But I'd wait for pushback from committee members first -- if nothing else, the question provides something for the people who need to bikeshed on syntax to bikeshed on.

**Comment by bathos** [comment]
Both ! and ~ have the NLTH problem — and it is a problem, I suspect, because the syntax seems to be intended to be analogous to sync ops that are commonly formatted like this:

```js
something()
  .somethingElse()
  .anotherThing();
```

It would be one thing if it threw, but with `!` or `~`, it _wouldn’t_ throw (well, at least not for the ‘right’ reason).

**Comment by michaelfig** [comment]
Since `!.` is coopted by TypeScript, maybe we could have something like:

```js
something()
   ~.somethingElse()
   ~.[123]
   ~.(arg1, arg2)
   ~.anotherThing();
```

**Comment by ljharb** [comment]
Tilde is already a bitwise operator, is it not?

**Comment by ljharb** [comment]
The issue for me with ! isn’t really syntactic conflict with typescript, it’s that it has a number of common meanings (conventional and syntactic) across many programming languages, none of which overlap with this proposal’s semantics.

I’ve seen it mean negation (everywhere), asserting that no exception will be thrown (typescript, ecma-262 notation), mutation or danger (ruby, swift), and asserting that an exception *will* be thrown on failure (rails), factorial (math), etc. While I’m sure this is not an exhaustive list and I’m sure I’ve missed some, i think using the exclamation point for a less-than-universal meaning will create a large amount of confusion.

**Comment by erights** [comment]
> none of which overlap with this proposal’s semantics.

`!` is used as the send operator in Tony Hoare's CSP and in many languages that descend from or are influenced by CSP, including Occam. Erlang, Pi Calculus, Pict. (what about Scala? Go?) In Erlang `!` means asynchronous send with Actor-like semantics, which is very close.

**Comment by ljharb** [comment]
Thanks, that’s helpful - which familiar meanings of ! (alternatively, which other familiar languages) do you expect will be predominant in the wider javascript community?

**Comment by erights** [comment]
The other meanings for infix bang that you mention, in aggregate, probably exceeds total CSP-derived usage by a good deal. But I doubt any one of those meanings do. Erlang gets significant use. Many people learn Pi Calculus in school.

In any case, alternative suggestions welcome. Let the bikeshedding begin!

Btw, I hate `~.` . Whatever the operator is, it should suggest the meaning. In E I used `<-`, but this won't work in JavaScript because `a<-b` already means `a < -b`.

**Comment by bathos** [comment]
> Whatever the operator is, it should suggest the meaning.

`foo🥠(bar)`

**Comment by michaelfig** [comment]
If we don't worry about Typescript, I'd use `!.` as the operator, and not have any [nlth] handling.  It's easier to explain to people (`!.' is an eventual `.`), and works well for the split-line case (just insert or remove `!` to change from sync to async or back to sync).

```
a
  !.foo(a, b, c)
  !.bar
  !.[123]
  !.(a, b, c)
```

all results in SyntaxErrors in current Javascript.  The only seeming ambiguity between infix `!.` and prefix `!` is `!.1`, but that is not valid `!.` syntax anyway, because of the literal digit (and doubly so if it appears in infix position).

I only suggested `~.` (wavy dot) because prefix `~` (bitwise not) is much less used than `!`.

And almost nobody would actually write `~.1` or `!.1` in real code unless they want to win the obfuscated Javascript competition.

**Comment by ljharb** [comment]
There’s quite a lot of the web that depends on those kind of obfuscation patterns, i suspect.

**Comment by michaelfig** [comment]
Maybe `.!`, which would need to appear as a single token (no whitespace between them) and hence not conflict with existing Javascript.

```
a
   .!foo(a, b, c)
   .!bar
   .![123]
   .!(a, b, c)
delete a.!bar;
a.!bar = 'baz';
```

The only conflict would be with Typescript, if somebody wanted to write the (useless) code `123.!['toString']`, which compiles to `123.[to assert that the numeric literal `123.` was not null and return the 'toString' property of that literal.  The same thing can be written in both Javascript and Typescript as `123['toString']` without any conflict.  It's only that specific combination of a trailing dot and not-null assertion followed by a computed index that would be evaluated differently, as `Promise.resolve(123.).get('toString')`.

I don't think the Typescript community would be upset with the loss of that particular use.

**Comment by katelynsills** [comment]
For what it is worth, there's a proposal already for "[Optional Chaining"](https://github.com/babel/proposals#optional-chaining) and they use the syntax `obj?.prop`. Typescript worries aside, I wonder if it would be helpful to use similar syntax for infix bang, going to Michael's suggestion of `!.` above.

**Comment by hax** [comment]
I think we'd better do not use `!.` because TypeScript already take it (postfix `!`) and some other mainstream languages also have it (Swift forced unwrapping use post `!`, Kotlin use postfix `!!`, Dart plan to add postfix `!`).

It's also not a good idea to use `!` `.!` `!!` because there are too close to `!.` 😂

I would suggest use `^.` . I remember `^` used to be an option of async operator.

**Comment by hax** [comment]
BTW, the endline of README 
> The ECMAScript optional chaining proposal may mitigate the need for non-null assertion in that circumstance

is not correct IMO. Optional chaining and non-null assertion are complementary, so landing optional chaining actually ask for non-null assertion (or immediate null check if also consider runtime semantic).

**Comment by wmertens** [comment]
What about semi-overloading `>`?  It evokes "derive from" for me.

```js
a
   .foo(a, b, c)
   >.bar
   >.[123]
   >.(a, b, c)
delete a>.bar;
a>.bar = 'baz';
```

It semi-conflicts with `a > .3` but I think in this case that's fine, a number will never be on the right side of `>.`.

**Comment by warner** [comment]
Christopher Mooney (@godsflaw) made a cogent point on Twitter: SSH treats `~` as an escape  character (only at the beginning of a line), and `~.` is the "close the connection" command. If you ever type `<newline> ~ .`, with nothing else in between, the ssh session will be immediately terminated. So if you're editing code over SSH, and your editor auto-indents lines for you, and you're using this sort of multi-line chaining pattern:

```js
  target
    .method1()
    .method2()
    .method3();
```

with wavydot, then you'll be typing `<newline> ~ .` on each line, and your entire session will terminate.

SSH can be configured to use a different character, or disable the feature altogether, but that will be pretty uncommon.

**Comment by warner** [comment]
Another data point:  our [super-scientific twitter poll](https://twitter.com/agoric/status/1177724731828498434) shows "tildot" being the preferred pronounciation of `~.`, a clear favorite over "wavy-dot", "twiddle-dot", and "squiggle-spot".

**Comment by FUDCo** [comment]
I still vote for "smoosh".

**Comment by michaelfig** [comment]
Closing for now, unless something resurrects this thread.
